/*
 * generated by Xtext 2.12.0
 */
package fr.n7.simplepdl.txt.ide.contentassist.antlr;

import com.google.inject.Inject;
import fr.n7.simplepdl.txt.ide.contentassist.antlr.internal.InternalPDLParser;
import fr.n7.simplepdl.txt.services.PDLGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PDLParser extends AbstractContentAssistParser {

	@Inject
	private PDLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPDLParser createParser() {
		InternalPDLParser result = new InternalPDLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProcessElementAccess().getAlternatives(), "rule__ProcessElement__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getWorkSequenceTypeAccess().getAlternatives(), "rule__WorkSequenceType__Alternatives");
					put(grammarAccess.getProcessAccess().getGroup(), "rule__Process__Group__0");
					put(grammarAccess.getProcessAccess().getGroup_4(), "rule__Process__Group_4__0");
					put(grammarAccess.getProcessAccess().getGroup_4_3(), "rule__Process__Group_4_3__0");
					put(grammarAccess.getWorkDefinitionAccess().getGroup(), "rule__WorkDefinition__Group__0");
					put(grammarAccess.getWorkDefinitionAccess().getGroup_4(), "rule__WorkDefinition__Group_4__0");
					put(grammarAccess.getWorkDefinitionAccess().getGroup_4_3(), "rule__WorkDefinition__Group_4_3__0");
					put(grammarAccess.getWorkDefinitionAccess().getGroup_5(), "rule__WorkDefinition__Group_5__0");
					put(grammarAccess.getWorkDefinitionAccess().getGroup_5_3(), "rule__WorkDefinition__Group_5_3__0");
					put(grammarAccess.getWorkDefinitionAccess().getGroup_6(), "rule__WorkDefinition__Group_6__0");
					put(grammarAccess.getWorkDefinitionAccess().getGroup_6_3(), "rule__WorkDefinition__Group_6_3__0");
					put(grammarAccess.getWorkSequenceAccess().getGroup(), "rule__WorkSequence__Group__0");
					put(grammarAccess.getGuidanceAccess().getGroup(), "rule__Guidance__Group__0");
					put(grammarAccess.getGuidanceAccess().getGroup_4(), "rule__Guidance__Group_4__0");
					put(grammarAccess.getGuidanceAccess().getGroup_4_3(), "rule__Guidance__Group_4_3__0");
					put(grammarAccess.getResourcesAccess().getGroup(), "rule__Resources__Group__0");
					put(grammarAccess.getResourcesAccess().getGroup_5(), "rule__Resources__Group_5__0");
					put(grammarAccess.getResourcesAccess().getGroup_5_3(), "rule__Resources__Group_5_3__0");
					put(grammarAccess.getRequeteDeRessourceAccess().getGroup(), "rule__RequeteDeRessource__Group__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getProcessAccess().getNameAssignment_2(), "rule__Process__NameAssignment_2");
					put(grammarAccess.getProcessAccess().getProcessElementsAssignment_4_2(), "rule__Process__ProcessElementsAssignment_4_2");
					put(grammarAccess.getProcessAccess().getProcessElementsAssignment_4_3_1(), "rule__Process__ProcessElementsAssignment_4_3_1");
					put(grammarAccess.getWorkDefinitionAccess().getNameAssignment_2(), "rule__WorkDefinition__NameAssignment_2");
					put(grammarAccess.getWorkDefinitionAccess().getLinksToPredecessorsAssignment_4_2(), "rule__WorkDefinition__LinksToPredecessorsAssignment_4_2");
					put(grammarAccess.getWorkDefinitionAccess().getLinksToPredecessorsAssignment_4_3_1(), "rule__WorkDefinition__LinksToPredecessorsAssignment_4_3_1");
					put(grammarAccess.getWorkDefinitionAccess().getLinksToSuccessorsAssignment_5_2(), "rule__WorkDefinition__LinksToSuccessorsAssignment_5_2");
					put(grammarAccess.getWorkDefinitionAccess().getLinksToSuccessorsAssignment_5_3_1(), "rule__WorkDefinition__LinksToSuccessorsAssignment_5_3_1");
					put(grammarAccess.getWorkDefinitionAccess().getLinktoresourceAssignment_6_2(), "rule__WorkDefinition__LinktoresourceAssignment_6_2");
					put(grammarAccess.getWorkDefinitionAccess().getLinktoresourceAssignment_6_3_1(), "rule__WorkDefinition__LinktoresourceAssignment_6_3_1");
					put(grammarAccess.getWorkSequenceAccess().getLinkTypeAssignment_3(), "rule__WorkSequence__LinkTypeAssignment_3");
					put(grammarAccess.getWorkSequenceAccess().getPredecessorAssignment_5(), "rule__WorkSequence__PredecessorAssignment_5");
					put(grammarAccess.getWorkSequenceAccess().getSuccessorAssignment_7(), "rule__WorkSequence__SuccessorAssignment_7");
					put(grammarAccess.getGuidanceAccess().getTextAssignment_3(), "rule__Guidance__TextAssignment_3");
					put(grammarAccess.getGuidanceAccess().getElementsAssignment_4_2(), "rule__Guidance__ElementsAssignment_4_2");
					put(grammarAccess.getGuidanceAccess().getElementsAssignment_4_3_1(), "rule__Guidance__ElementsAssignment_4_3_1");
					put(grammarAccess.getResourcesAccess().getNameAssignment_1(), "rule__Resources__NameAssignment_1");
					put(grammarAccess.getResourcesAccess().getQuantiteAssignment_4(), "rule__Resources__QuantiteAssignment_4");
					put(grammarAccess.getResourcesAccess().getLinktoresourceAssignment_5_2(), "rule__Resources__LinktoresourceAssignment_5_2");
					put(grammarAccess.getResourcesAccess().getLinktoresourceAssignment_5_3_1(), "rule__Resources__LinktoresourceAssignment_5_3_1");
					put(grammarAccess.getRequeteDeRessourceAccess().getQuantiteAssignment_3(), "rule__RequeteDeRessource__QuantiteAssignment_3");
					put(grammarAccess.getRequeteDeRessourceAccess().getResourcesAssignment_5(), "rule__RequeteDeRessource__ResourcesAssignment_5");
					put(grammarAccess.getRequeteDeRessourceAccess().getWorkdefinitionAssignment_7(), "rule__RequeteDeRessource__WorkdefinitionAssignment_7");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
