/**
 * generated by Xtext 2.12.0
 */
package fr.n7.simplepdl.txt.ide;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PDLIdeSetup /* implements PDLStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nPDLRuntimeModule cannot be resolved.");
  }
}
