/*
 * generated by Xtext 2.12.0
 */
package fr.n7.simplepdl.txt.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PDLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProcessAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProcessKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cProcessElementsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cProcessElementsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cProcessElementsProcessElementParserRuleCall_4_2_0 = (RuleCall)cProcessElementsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cProcessElementsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cProcessElementsProcessElementParserRuleCall_4_3_1_0 = (RuleCall)cProcessElementsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Process:
		//	{Process}
		//	'Process'
		//	name=EString
		//	'{' ('processElements' '{' processElements+=ProcessElement ("," processElements+=ProcessElement)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Process} 'Process' name=EString '{' ('processElements' '{' processElements+=ProcessElement (","
		//processElements+=ProcessElement)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Process}
		public Action getProcessAction_0() { return cProcessAction_0; }
		
		//'Process'
		public Keyword getProcessKeyword_1() { return cProcessKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('processElements' '{' processElements+=ProcessElement ("," processElements+=ProcessElement)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'processElements'
		public Keyword getProcessElementsKeyword_4_0() { return cProcessElementsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//processElements+=ProcessElement
		public Assignment getProcessElementsAssignment_4_2() { return cProcessElementsAssignment_4_2; }
		
		//ProcessElement
		public RuleCall getProcessElementsProcessElementParserRuleCall_4_2_0() { return cProcessElementsProcessElementParserRuleCall_4_2_0; }
		
		//("," processElements+=ProcessElement)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//processElements+=ProcessElement
		public Assignment getProcessElementsAssignment_4_3_1() { return cProcessElementsAssignment_4_3_1; }
		
		//ProcessElement
		public RuleCall getProcessElementsProcessElementParserRuleCall_4_3_1_0() { return cProcessElementsProcessElementParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ProcessElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.ProcessElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cWorkDefinitionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWorkSequenceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cGuidanceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cResourcesParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRequeteDeRessourceParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//ProcessElement:
		//	WorkDefinition | WorkSequence | Guidance | Resources | RequeteDeRessource;
		@Override public ParserRule getRule() { return rule; }
		
		//WorkDefinition | WorkSequence | Guidance | Resources | RequeteDeRessource
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//WorkDefinition
		public RuleCall getWorkDefinitionParserRuleCall_0() { return cWorkDefinitionParserRuleCall_0; }
		
		//WorkSequence
		public RuleCall getWorkSequenceParserRuleCall_1() { return cWorkSequenceParserRuleCall_1; }
		
		//Guidance
		public RuleCall getGuidanceParserRuleCall_2() { return cGuidanceParserRuleCall_2; }
		
		//Resources
		public RuleCall getResourcesParserRuleCall_3() { return cResourcesParserRuleCall_3; }
		
		//RequeteDeRessource
		public RuleCall getRequeteDeRessourceParserRuleCall_4() { return cRequeteDeRessourceParserRuleCall_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class WorkDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.WorkDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWorkDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cWorkDefinitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLinksToPredecessorsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cLinksToPredecessorsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cLinksToPredecessorsWorkSequenceCrossReference_4_2_0 = (CrossReference)cLinksToPredecessorsAssignment_4_2.eContents().get(0);
		private final RuleCall cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1 = (RuleCall)cLinksToPredecessorsWorkSequenceCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cLinksToPredecessorsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0 = (CrossReference)cLinksToPredecessorsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLinksToSuccessorsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLinksToSuccessorsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cLinksToSuccessorsWorkSequenceCrossReference_5_2_0 = (CrossReference)cLinksToSuccessorsAssignment_5_2.eContents().get(0);
		private final RuleCall cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1 = (RuleCall)cLinksToSuccessorsWorkSequenceCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLinksToSuccessorsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0 = (CrossReference)cLinksToSuccessorsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLinktoresourceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cLinktoresourceAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cLinktoresourceRequeteDeRessourceCrossReference_6_2_0 = (CrossReference)cLinktoresourceAssignment_6_2.eContents().get(0);
		private final RuleCall cLinktoresourceRequeteDeRessourceEStringParserRuleCall_6_2_0_1 = (RuleCall)cLinktoresourceRequeteDeRessourceCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cLinktoresourceAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cLinktoresourceRequeteDeRessourceCrossReference_6_3_1_0 = (CrossReference)cLinktoresourceAssignment_6_3_1.eContents().get(0);
		private final RuleCall cLinktoresourceRequeteDeRessourceEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cLinktoresourceRequeteDeRessourceCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//WorkDefinition:
		//	{WorkDefinition}
		//	'WorkDefinition'
		//	name=EString
		//	'{' ('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] (","
		//	linksToPredecessors+=[WorkSequence|EString])* ')')? ('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString]
		//	("," linksToSuccessors+=[WorkSequence|EString])* ')')? ('linktoresource' '('
		//	linktoresource+=[RequeteDeRessource|EString] ("," linktoresource+=[RequeteDeRessource|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{WorkDefinition} 'WorkDefinition' name=EString '{' ('linksToPredecessors' '('
		//linksToPredecessors+=[WorkSequence|EString] ("," linksToPredecessors+=[WorkSequence|EString])* ')')?
		//('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString] ("," linksToSuccessors+=[WorkSequence|EString])*
		//')')? ('linktoresource' '(' linktoresource+=[RequeteDeRessource|EString] (","
		//linktoresource+=[RequeteDeRessource|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{WorkDefinition}
		public Action getWorkDefinitionAction_0() { return cWorkDefinitionAction_0; }
		
		//'WorkDefinition'
		public Keyword getWorkDefinitionKeyword_1() { return cWorkDefinitionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] (","
		//linksToPredecessors+=[WorkSequence|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'linksToPredecessors'
		public Keyword getLinksToPredecessorsKeyword_4_0() { return cLinksToPredecessorsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//linksToPredecessors+=[WorkSequence|EString]
		public Assignment getLinksToPredecessorsAssignment_4_2() { return cLinksToPredecessorsAssignment_4_2; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToPredecessorsWorkSequenceCrossReference_4_2_0() { return cLinksToPredecessorsWorkSequenceCrossReference_4_2_0; }
		
		//EString
		public RuleCall getLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1() { return cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1; }
		
		//("," linksToPredecessors+=[WorkSequence|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//linksToPredecessors+=[WorkSequence|EString]
		public Assignment getLinksToPredecessorsAssignment_4_3_1() { return cLinksToPredecessorsAssignment_4_3_1; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0() { return cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1() { return cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString] ("," linksToSuccessors+=[WorkSequence|EString])*
		//')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'linksToSuccessors'
		public Keyword getLinksToSuccessorsKeyword_5_0() { return cLinksToSuccessorsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//linksToSuccessors+=[WorkSequence|EString]
		public Assignment getLinksToSuccessorsAssignment_5_2() { return cLinksToSuccessorsAssignment_5_2; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToSuccessorsWorkSequenceCrossReference_5_2_0() { return cLinksToSuccessorsWorkSequenceCrossReference_5_2_0; }
		
		//EString
		public RuleCall getLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1() { return cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1; }
		
		//("," linksToSuccessors+=[WorkSequence|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//linksToSuccessors+=[WorkSequence|EString]
		public Assignment getLinksToSuccessorsAssignment_5_3_1() { return cLinksToSuccessorsAssignment_5_3_1; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0() { return cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1() { return cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('linktoresource' '(' linktoresource+=[RequeteDeRessource|EString] ("," linktoresource+=[RequeteDeRessource|EString])*
		//')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'linktoresource'
		public Keyword getLinktoresourceKeyword_6_0() { return cLinktoresourceKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//linktoresource+=[RequeteDeRessource|EString]
		public Assignment getLinktoresourceAssignment_6_2() { return cLinktoresourceAssignment_6_2; }
		
		//[RequeteDeRessource|EString]
		public CrossReference getLinktoresourceRequeteDeRessourceCrossReference_6_2_0() { return cLinktoresourceRequeteDeRessourceCrossReference_6_2_0; }
		
		//EString
		public RuleCall getLinktoresourceRequeteDeRessourceEStringParserRuleCall_6_2_0_1() { return cLinktoresourceRequeteDeRessourceEStringParserRuleCall_6_2_0_1; }
		
		//("," linktoresource+=[RequeteDeRessource|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//linktoresource+=[RequeteDeRessource|EString]
		public Assignment getLinktoresourceAssignment_6_3_1() { return cLinktoresourceAssignment_6_3_1; }
		
		//[RequeteDeRessource|EString]
		public CrossReference getLinktoresourceRequeteDeRessourceCrossReference_6_3_1_0() { return cLinktoresourceRequeteDeRessourceCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getLinktoresourceRequeteDeRessourceEStringParserRuleCall_6_3_1_0_1() { return cLinktoresourceRequeteDeRessourceEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class WorkSequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.WorkSequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWorkSequenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLinkTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLinkTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLinkTypeWorkSequenceTypeEnumRuleCall_3_0 = (RuleCall)cLinkTypeAssignment_3.eContents().get(0);
		private final Keyword cPredecessorKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPredecessorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cPredecessorWorkDefinitionCrossReference_5_0 = (CrossReference)cPredecessorAssignment_5.eContents().get(0);
		private final RuleCall cPredecessorWorkDefinitionEStringParserRuleCall_5_0_1 = (RuleCall)cPredecessorWorkDefinitionCrossReference_5_0.eContents().get(1);
		private final Keyword cSuccessorKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSuccessorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cSuccessorWorkDefinitionCrossReference_7_0 = (CrossReference)cSuccessorAssignment_7.eContents().get(0);
		private final RuleCall cSuccessorWorkDefinitionEStringParserRuleCall_7_0_1 = (RuleCall)cSuccessorWorkDefinitionCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//WorkSequence:
		//	'WorkSequence'
		//	'{'
		//	'linkType' linkType=WorkSequenceType
		//	'predecessor' predecessor=[WorkDefinition|EString]
		//	'successor' successor=[WorkDefinition|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'WorkSequence' '{' 'linkType' linkType=WorkSequenceType 'predecessor' predecessor=[WorkDefinition|EString] 'successor'
		//successor=[WorkDefinition|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'WorkSequence'
		public Keyword getWorkSequenceKeyword_0() { return cWorkSequenceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'linkType'
		public Keyword getLinkTypeKeyword_2() { return cLinkTypeKeyword_2; }
		
		//linkType=WorkSequenceType
		public Assignment getLinkTypeAssignment_3() { return cLinkTypeAssignment_3; }
		
		//WorkSequenceType
		public RuleCall getLinkTypeWorkSequenceTypeEnumRuleCall_3_0() { return cLinkTypeWorkSequenceTypeEnumRuleCall_3_0; }
		
		//'predecessor'
		public Keyword getPredecessorKeyword_4() { return cPredecessorKeyword_4; }
		
		//predecessor=[WorkDefinition|EString]
		public Assignment getPredecessorAssignment_5() { return cPredecessorAssignment_5; }
		
		//[WorkDefinition|EString]
		public CrossReference getPredecessorWorkDefinitionCrossReference_5_0() { return cPredecessorWorkDefinitionCrossReference_5_0; }
		
		//EString
		public RuleCall getPredecessorWorkDefinitionEStringParserRuleCall_5_0_1() { return cPredecessorWorkDefinitionEStringParserRuleCall_5_0_1; }
		
		//'successor'
		public Keyword getSuccessorKeyword_6() { return cSuccessorKeyword_6; }
		
		//successor=[WorkDefinition|EString]
		public Assignment getSuccessorAssignment_7() { return cSuccessorAssignment_7; }
		
		//[WorkDefinition|EString]
		public CrossReference getSuccessorWorkDefinitionCrossReference_7_0() { return cSuccessorWorkDefinitionCrossReference_7_0; }
		
		//EString
		public RuleCall getSuccessorWorkDefinitionEStringParserRuleCall_7_0_1() { return cSuccessorWorkDefinitionEStringParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class GuidanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.Guidance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGuidanceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTextKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextEStringParserRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cElementsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cElementsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cElementsProcessElementCrossReference_4_2_0 = (CrossReference)cElementsAssignment_4_2.eContents().get(0);
		private final RuleCall cElementsProcessElementEStringParserRuleCall_4_2_0_1 = (RuleCall)cElementsProcessElementCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cElementsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cElementsProcessElementCrossReference_4_3_1_0 = (CrossReference)cElementsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cElementsProcessElementEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cElementsProcessElementCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Guidance:
		//	'Guidance'
		//	'{'
		//	'text' text=EString ('elements' '(' elements+=[ProcessElement|EString] ("," elements+=[ProcessElement|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Guidance' '{' 'text' text=EString ('elements' '(' elements+=[ProcessElement|EString] (","
		//elements+=[ProcessElement|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//'Guidance'
		public Keyword getGuidanceKeyword_0() { return cGuidanceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'text'
		public Keyword getTextKeyword_2() { return cTextKeyword_2; }
		
		//text=EString
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_3_0() { return cTextEStringParserRuleCall_3_0; }
		
		//('elements' '(' elements+=[ProcessElement|EString] ("," elements+=[ProcessElement|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'elements'
		public Keyword getElementsKeyword_4_0() { return cElementsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//elements+=[ProcessElement|EString]
		public Assignment getElementsAssignment_4_2() { return cElementsAssignment_4_2; }
		
		//[ProcessElement|EString]
		public CrossReference getElementsProcessElementCrossReference_4_2_0() { return cElementsProcessElementCrossReference_4_2_0; }
		
		//EString
		public RuleCall getElementsProcessElementEStringParserRuleCall_4_2_0_1() { return cElementsProcessElementEStringParserRuleCall_4_2_0_1; }
		
		//("," elements+=[ProcessElement|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//elements+=[ProcessElement|EString]
		public Assignment getElementsAssignment_4_3_1() { return cElementsAssignment_4_3_1; }
		
		//[ProcessElement|EString]
		public CrossReference getElementsProcessElementCrossReference_4_3_1_0() { return cElementsProcessElementCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getElementsProcessElementEStringParserRuleCall_4_3_1_0_1() { return cElementsProcessElementEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ResourcesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.Resources");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourcesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuantiteKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cQuantiteAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cQuantiteEIntParserRuleCall_4_0 = (RuleCall)cQuantiteAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLinktoresourceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLinktoresourceAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cLinktoresourceRequeteDeRessourceCrossReference_5_2_0 = (CrossReference)cLinktoresourceAssignment_5_2.eContents().get(0);
		private final RuleCall cLinktoresourceRequeteDeRessourceEStringParserRuleCall_5_2_0_1 = (RuleCall)cLinktoresourceRequeteDeRessourceCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLinktoresourceAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cLinktoresourceRequeteDeRessourceCrossReference_5_3_1_0 = (CrossReference)cLinktoresourceAssignment_5_3_1.eContents().get(0);
		private final RuleCall cLinktoresourceRequeteDeRessourceEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cLinktoresourceRequeteDeRessourceCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Resources:
		//	'Resources'
		//	name=EString
		//	'{'
		//	'quantite' quantite=EInt ('linktoresource' '(' linktoresource+=[RequeteDeRessource|EString] (","
		//	linktoresource+=[RequeteDeRessource|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Resources' name=EString '{' 'quantite' quantite=EInt ('linktoresource' '(' linktoresource+=[RequeteDeRessource|EString]
		//("," linktoresource+=[RequeteDeRessource|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//'Resources'
		public Keyword getResourcesKeyword_0() { return cResourcesKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'quantite'
		public Keyword getQuantiteKeyword_3() { return cQuantiteKeyword_3; }
		
		//quantite=EInt
		public Assignment getQuantiteAssignment_4() { return cQuantiteAssignment_4; }
		
		//EInt
		public RuleCall getQuantiteEIntParserRuleCall_4_0() { return cQuantiteEIntParserRuleCall_4_0; }
		
		//('linktoresource' '(' linktoresource+=[RequeteDeRessource|EString] ("," linktoresource+=[RequeteDeRessource|EString])*
		//')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'linktoresource'
		public Keyword getLinktoresourceKeyword_5_0() { return cLinktoresourceKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//linktoresource+=[RequeteDeRessource|EString]
		public Assignment getLinktoresourceAssignment_5_2() { return cLinktoresourceAssignment_5_2; }
		
		//[RequeteDeRessource|EString]
		public CrossReference getLinktoresourceRequeteDeRessourceCrossReference_5_2_0() { return cLinktoresourceRequeteDeRessourceCrossReference_5_2_0; }
		
		//EString
		public RuleCall getLinktoresourceRequeteDeRessourceEStringParserRuleCall_5_2_0_1() { return cLinktoresourceRequeteDeRessourceEStringParserRuleCall_5_2_0_1; }
		
		//("," linktoresource+=[RequeteDeRessource|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//linktoresource+=[RequeteDeRessource|EString]
		public Assignment getLinktoresourceAssignment_5_3_1() { return cLinktoresourceAssignment_5_3_1; }
		
		//[RequeteDeRessource|EString]
		public CrossReference getLinktoresourceRequeteDeRessourceCrossReference_5_3_1_0() { return cLinktoresourceRequeteDeRessourceCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getLinktoresourceRequeteDeRessourceEStringParserRuleCall_5_3_1_0_1() { return cLinktoresourceRequeteDeRessourceEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class RequeteDeRessourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.RequeteDeRessource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRequeteDeRessourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cQuantiteKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cQuantiteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQuantiteEIntParserRuleCall_3_0 = (RuleCall)cQuantiteAssignment_3.eContents().get(0);
		private final Keyword cResourcesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cResourcesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cResourcesResourcesCrossReference_5_0 = (CrossReference)cResourcesAssignment_5.eContents().get(0);
		private final RuleCall cResourcesResourcesEStringParserRuleCall_5_0_1 = (RuleCall)cResourcesResourcesCrossReference_5_0.eContents().get(1);
		private final Keyword cWorkdefinitionKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cWorkdefinitionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cWorkdefinitionWorkDefinitionCrossReference_7_0 = (CrossReference)cWorkdefinitionAssignment_7.eContents().get(0);
		private final RuleCall cWorkdefinitionWorkDefinitionEStringParserRuleCall_7_0_1 = (RuleCall)cWorkdefinitionWorkDefinitionCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//RequeteDeRessource:
		//	'RequeteDeRessource'
		//	'{'
		//	'quantite' quantite=EInt
		//	'resources' resources=[Resources|EString]
		//	'workdefinition' workdefinition=[WorkDefinition|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'RequeteDeRessource' '{' 'quantite' quantite=EInt 'resources' resources=[Resources|EString] 'workdefinition'
		//workdefinition=[WorkDefinition|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'RequeteDeRessource'
		public Keyword getRequeteDeRessourceKeyword_0() { return cRequeteDeRessourceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'quantite'
		public Keyword getQuantiteKeyword_2() { return cQuantiteKeyword_2; }
		
		//quantite=EInt
		public Assignment getQuantiteAssignment_3() { return cQuantiteAssignment_3; }
		
		//EInt
		public RuleCall getQuantiteEIntParserRuleCall_3_0() { return cQuantiteEIntParserRuleCall_3_0; }
		
		//'resources'
		public Keyword getResourcesKeyword_4() { return cResourcesKeyword_4; }
		
		//resources=[Resources|EString]
		public Assignment getResourcesAssignment_5() { return cResourcesAssignment_5; }
		
		//[Resources|EString]
		public CrossReference getResourcesResourcesCrossReference_5_0() { return cResourcesResourcesCrossReference_5_0; }
		
		//EString
		public RuleCall getResourcesResourcesEStringParserRuleCall_5_0_1() { return cResourcesResourcesEStringParserRuleCall_5_0_1; }
		
		//'workdefinition'
		public Keyword getWorkdefinitionKeyword_6() { return cWorkdefinitionKeyword_6; }
		
		//workdefinition=[WorkDefinition|EString]
		public Assignment getWorkdefinitionAssignment_7() { return cWorkdefinitionAssignment_7; }
		
		//[WorkDefinition|EString]
		public CrossReference getWorkdefinitionWorkDefinitionCrossReference_7_0() { return cWorkdefinitionWorkDefinitionCrossReference_7_0; }
		
		//EString
		public RuleCall getWorkdefinitionWorkDefinitionEStringParserRuleCall_7_0_1() { return cWorkdefinitionWorkDefinitionEStringParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class WorkSequenceTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.WorkSequenceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStartToStartEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStartToStartStartToStartKeyword_0_0 = (Keyword)cStartToStartEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFinishToStartEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFinishToStartFinishToStartKeyword_1_0 = (Keyword)cFinishToStartEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStartToFinishEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStartToFinishStartToFinishKeyword_2_0 = (Keyword)cStartToFinishEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFinishToFinishEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFinishToFinishFinishToFinishKeyword_3_0 = (Keyword)cFinishToFinishEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum WorkSequenceType:
		//	startToStart | finishToStart | startToFinish | finishToFinish;
		public EnumRule getRule() { return rule; }
		
		//startToStart | finishToStart | startToFinish | finishToFinish
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//startToStart
		public EnumLiteralDeclaration getStartToStartEnumLiteralDeclaration_0() { return cStartToStartEnumLiteralDeclaration_0; }
		
		//'startToStart'
		public Keyword getStartToStartStartToStartKeyword_0_0() { return cStartToStartStartToStartKeyword_0_0; }
		
		//finishToStart
		public EnumLiteralDeclaration getFinishToStartEnumLiteralDeclaration_1() { return cFinishToStartEnumLiteralDeclaration_1; }
		
		//'finishToStart'
		public Keyword getFinishToStartFinishToStartKeyword_1_0() { return cFinishToStartFinishToStartKeyword_1_0; }
		
		//startToFinish
		public EnumLiteralDeclaration getStartToFinishEnumLiteralDeclaration_2() { return cStartToFinishEnumLiteralDeclaration_2; }
		
		//'startToFinish'
		public Keyword getStartToFinishStartToFinishKeyword_2_0() { return cStartToFinishStartToFinishKeyword_2_0; }
		
		//finishToFinish
		public EnumLiteralDeclaration getFinishToFinishEnumLiteralDeclaration_3() { return cFinishToFinishEnumLiteralDeclaration_3; }
		
		//'finishToFinish'
		public Keyword getFinishToFinishFinishToFinishKeyword_3_0() { return cFinishToFinishFinishToFinishKeyword_3_0; }
	}
	
	private final ProcessElements pProcess;
	private final ProcessElementElements pProcessElement;
	private final EStringElements pEString;
	private final WorkDefinitionElements pWorkDefinition;
	private final WorkSequenceElements pWorkSequence;
	private final GuidanceElements pGuidance;
	private final ResourcesElements pResources;
	private final RequeteDeRessourceElements pRequeteDeRessource;
	private final WorkSequenceTypeElements eWorkSequenceType;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProcess = new ProcessElements();
		this.pProcessElement = new ProcessElementElements();
		this.pEString = new EStringElements();
		this.pWorkDefinition = new WorkDefinitionElements();
		this.pWorkSequence = new WorkSequenceElements();
		this.pGuidance = new GuidanceElements();
		this.pResources = new ResourcesElements();
		this.pRequeteDeRessource = new RequeteDeRessourceElements();
		this.eWorkSequenceType = new WorkSequenceTypeElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.n7.simplepdl.txt.PDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Process:
	//	{Process}
	//	'Process'
	//	name=EString
	//	'{' ('processElements' '{' processElements+=ProcessElement ("," processElements+=ProcessElement)* '}')?
	//	'}';
	public ProcessElements getProcessAccess() {
		return pProcess;
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//ProcessElement:
	//	WorkDefinition | WorkSequence | Guidance | Resources | RequeteDeRessource;
	public ProcessElementElements getProcessElementAccess() {
		return pProcessElement;
	}
	
	public ParserRule getProcessElementRule() {
		return getProcessElementAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//WorkDefinition:
	//	{WorkDefinition}
	//	'WorkDefinition'
	//	name=EString
	//	'{' ('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] (","
	//	linksToPredecessors+=[WorkSequence|EString])* ')')? ('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString]
	//	("," linksToSuccessors+=[WorkSequence|EString])* ')')? ('linktoresource' '('
	//	linktoresource+=[RequeteDeRessource|EString] ("," linktoresource+=[RequeteDeRessource|EString])* ')')?
	//	'}';
	public WorkDefinitionElements getWorkDefinitionAccess() {
		return pWorkDefinition;
	}
	
	public ParserRule getWorkDefinitionRule() {
		return getWorkDefinitionAccess().getRule();
	}
	
	//WorkSequence:
	//	'WorkSequence'
	//	'{'
	//	'linkType' linkType=WorkSequenceType
	//	'predecessor' predecessor=[WorkDefinition|EString]
	//	'successor' successor=[WorkDefinition|EString]
	//	'}';
	public WorkSequenceElements getWorkSequenceAccess() {
		return pWorkSequence;
	}
	
	public ParserRule getWorkSequenceRule() {
		return getWorkSequenceAccess().getRule();
	}
	
	//Guidance:
	//	'Guidance'
	//	'{'
	//	'text' text=EString ('elements' '(' elements+=[ProcessElement|EString] ("," elements+=[ProcessElement|EString])* ')')?
	//	'}';
	public GuidanceElements getGuidanceAccess() {
		return pGuidance;
	}
	
	public ParserRule getGuidanceRule() {
		return getGuidanceAccess().getRule();
	}
	
	//Resources:
	//	'Resources'
	//	name=EString
	//	'{'
	//	'quantite' quantite=EInt ('linktoresource' '(' linktoresource+=[RequeteDeRessource|EString] (","
	//	linktoresource+=[RequeteDeRessource|EString])* ')')?
	//	'}';
	public ResourcesElements getResourcesAccess() {
		return pResources;
	}
	
	public ParserRule getResourcesRule() {
		return getResourcesAccess().getRule();
	}
	
	//RequeteDeRessource:
	//	'RequeteDeRessource'
	//	'{'
	//	'quantite' quantite=EInt
	//	'resources' resources=[Resources|EString]
	//	'workdefinition' workdefinition=[WorkDefinition|EString]
	//	'}';
	public RequeteDeRessourceElements getRequeteDeRessourceAccess() {
		return pRequeteDeRessource;
	}
	
	public ParserRule getRequeteDeRessourceRule() {
		return getRequeteDeRessourceAccess().getRule();
	}
	
	//enum WorkSequenceType:
	//	startToStart | finishToStart | startToFinish | finishToFinish;
	public WorkSequenceTypeElements getWorkSequenceTypeAccess() {
		return eWorkSequenceType;
	}
	
	public EnumRule getWorkSequenceTypeRule() {
		return getWorkSequenceTypeAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
